version: '3.9'
services:
  backend:
    build: ./backend
    container_name: backend
    tty: true
    command: >
      sh -c "
        go build &&
        ./webauthn-sample-backend
      "
    ports:
      - 1323:1323
    volumes:
      - ./backend:/go/src
  frontend:
    build: ./frontend
    container_name: frontend
    tty: true
    volumes:
      - ./frontend:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app
    command: >
      sh -c "
        yarn &&
        yarn dev
      "
    ports:
      - 5173:5173

volumes:
  node_modules: