version: '3'
services:
  golang:
    build: ./backend
    container_name: backend
    tty: true
    command: >
      sh -c "
        go build &&
        ./webauthn-sample-backend
      "
    ports:
      - 1323:1323
    volumes:
      - ./backend:/go/src